/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RepaymentsRouteImport } from './routes/repayments'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBorrowersRouteImport } from './routes/admin.borrowers'
import { Route as AdminLoansRouteImport } from './routes/admin.loans'
import { Route as AdminRepaymentsRouteImport } from './routes/admin.repayments'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as LegalBorrowerAgreementRouteImport } from './routes/legal.borrower-agreement'
import { Route as LegalBvnConsentRouteImport } from './routes/legal.bvn-consent'
import { Route as LegalDebtRecoveryRouteImport } from './routes/legal.debt-recovery'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalSlaRouteImport } from './routes/legal.sla'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LoansIndexRouteImport } from './routes/loans.index'
import { Route as LoansLoanIdRouteImport } from './routes/loans.$loanId'
import { Route as LoansApplyRouteImport } from './routes/loans.apply'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RepaymentsRoute = RepaymentsRouteImport.update({
  id: '/repayments',
  path: '/repayments',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBorrowersRoute = AdminBorrowersRouteImport.update({
  id: '/admin/borrowers',
  path: '/admin/borrowers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoansRoute = AdminLoansRouteImport.update({
  id: '/admin/loans',
  path: '/admin/loans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRepaymentsRoute = AdminRepaymentsRouteImport.update({
  id: '/admin/repayments',
  path: '/admin/repayments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalBorrowerAgreementRoute = LegalBorrowerAgreementRouteImport.update({
  id: '/legal/borrower-agreement',
  path: '/legal/borrower-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalBvnConsentRoute = LegalBvnConsentRouteImport.update({
  id: '/legal/bvn-consent',
  path: '/legal/bvn-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDebtRecoveryRoute = LegalDebtRecoveryRouteImport.update({
  id: '/legal/debt-recovery',
  path: '/legal/debt-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlaRoute = LegalSlaRouteImport.update({
  id: '/legal/sla',
  path: '/legal/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansIndexRoute = LoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansLoanIdRoute = LoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => rootRouteImport,
} as any)
const LoansApplyRoute = LoansApplyRouteImport.update({
  id: '/loans/apply',
  path: '/loans/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/repayments': typeof RepaymentsRoute
  '/support': typeof SupportRoute
  '/admin/borrowers': typeof AdminBorrowersRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/repayments': typeof AdminRepaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/legal/borrower-agreement': typeof LegalBorrowerAgreementRoute
  '/legal/bvn-consent': typeof LegalBvnConsentRoute
  '/legal/debt-recovery': typeof LegalDebtRecoveryRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/sla': typeof LegalSlaRoute
  '/legal/terms': typeof LegalTermsRoute
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/apply': typeof LoansApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/repayments': typeof RepaymentsRoute
  '/support': typeof SupportRoute
  '/admin/borrowers': typeof AdminBorrowersRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/repayments': typeof AdminRepaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/legal/borrower-agreement': typeof LegalBorrowerAgreementRoute
  '/legal/bvn-consent': typeof LegalBvnConsentRoute
  '/legal/debt-recovery': typeof LegalDebtRecoveryRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/sla': typeof LegalSlaRoute
  '/legal/terms': typeof LegalTermsRoute
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/apply': typeof LoansApplyRoute
  '/admin': typeof AdminIndexRoute
  '/loans': typeof LoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/repayments': typeof RepaymentsRoute
  '/support': typeof SupportRoute
  '/admin/borrowers': typeof AdminBorrowersRoute
  '/admin/loans': typeof AdminLoansRoute
  '/admin/repayments': typeof AdminRepaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/legal/borrower-agreement': typeof LegalBorrowerAgreementRoute
  '/legal/bvn-consent': typeof LegalBvnConsentRoute
  '/legal/debt-recovery': typeof LegalDebtRecoveryRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/sla': typeof LegalSlaRoute
  '/legal/terms': typeof LegalTermsRoute
  '/loans/$loanId': typeof LoansLoanIdRoute
  '/loans/apply': typeof LoansApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/loans/': typeof LoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/repayments'
    | '/support'
    | '/admin/borrowers'
    | '/admin/loans'
    | '/admin/repayments'
    | '/admin/settings'
    | '/legal/borrower-agreement'
    | '/legal/bvn-consent'
    | '/legal/debt-recovery'
    | '/legal/privacy'
    | '/legal/sla'
    | '/legal/terms'
    | '/loans/$loanId'
    | '/loans/apply'
    | '/admin/'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/repayments'
    | '/support'
    | '/admin/borrowers'
    | '/admin/loans'
    | '/admin/repayments'
    | '/admin/settings'
    | '/legal/borrower-agreement'
    | '/legal/bvn-consent'
    | '/legal/debt-recovery'
    | '/legal/privacy'
    | '/legal/sla'
    | '/legal/terms'
    | '/loans/$loanId'
    | '/loans/apply'
    | '/admin'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/repayments'
    | '/support'
    | '/admin/borrowers'
    | '/admin/loans'
    | '/admin/repayments'
    | '/admin/settings'
    | '/legal/borrower-agreement'
    | '/legal/bvn-consent'
    | '/legal/debt-recovery'
    | '/legal/privacy'
    | '/legal/sla'
    | '/legal/terms'
    | '/loans/$loanId'
    | '/loans/apply'
    | '/admin/'
    | '/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RepaymentsRoute: typeof RepaymentsRoute
  SupportRoute: typeof SupportRoute
  AdminBorrowersRoute: typeof AdminBorrowersRoute
  AdminLoansRoute: typeof AdminLoansRoute
  AdminRepaymentsRoute: typeof AdminRepaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  LegalBorrowerAgreementRoute: typeof LegalBorrowerAgreementRoute
  LegalBvnConsentRoute: typeof LegalBvnConsentRoute
  LegalDebtRecoveryRoute: typeof LegalDebtRecoveryRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalSlaRoute: typeof LegalSlaRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LoansLoanIdRoute: typeof LoansLoanIdRoute
  LoansApplyRoute: typeof LoansApplyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LoansIndexRoute: typeof LoansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repayments': {
      id: '/repayments'
      path: '/repayments'
      fullPath: '/repayments'
      preLoaderRoute: typeof RepaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/borrowers': {
      id: '/admin/borrowers'
      path: '/admin/borrowers'
      fullPath: '/admin/borrowers'
      preLoaderRoute: typeof AdminBorrowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/loans': {
      id: '/admin/loans'
      path: '/admin/loans'
      fullPath: '/admin/loans'
      preLoaderRoute: typeof AdminLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/repayments': {
      id: '/admin/repayments'
      path: '/admin/repayments'
      fullPath: '/admin/repayments'
      preLoaderRoute: typeof AdminRepaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/borrower-agreement': {
      id: '/legal/borrower-agreement'
      path: '/legal/borrower-agreement'
      fullPath: '/legal/borrower-agreement'
      preLoaderRoute: typeof LegalBorrowerAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/bvn-consent': {
      id: '/legal/bvn-consent'
      path: '/legal/bvn-consent'
      fullPath: '/legal/bvn-consent'
      preLoaderRoute: typeof LegalBvnConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/debt-recovery': {
      id: '/legal/debt-recovery'
      path: '/legal/debt-recovery'
      fullPath: '/legal/debt-recovery'
      preLoaderRoute: typeof LegalDebtRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/sla': {
      id: '/legal/sla'
      path: '/legal/sla'
      fullPath: '/legal/sla'
      preLoaderRoute: typeof LegalSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/': {
      id: '/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof LoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/$loanId': {
      id: '/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof LoansLoanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loans/apply': {
      id: '/loans/apply'
      path: '/loans/apply'
      fullPath: '/loans/apply'
      preLoaderRoute: typeof LoansApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RepaymentsRoute: RepaymentsRoute,
  SupportRoute: SupportRoute,
  AdminBorrowersRoute: AdminBorrowersRoute,
  AdminLoansRoute: AdminLoansRoute,
  AdminRepaymentsRoute: AdminRepaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  LegalBorrowerAgreementRoute: LegalBorrowerAgreementRoute,
  LegalBvnConsentRoute: LegalBvnConsentRoute,
  LegalDebtRecoveryRoute: LegalDebtRecoveryRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalSlaRoute: LegalSlaRoute,
  LegalTermsRoute: LegalTermsRoute,
  LoansLoanIdRoute: LoansLoanIdRoute,
  LoansApplyRoute: LoansApplyRoute,
  AdminIndexRoute: AdminIndexRoute,
  LoansIndexRoute: LoansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
